# YAML for launching peer0 netflix
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: org1peer0
  labels:
    run: org1peer0
spec:
  serviceName: org1peer0
  replicas: 1
  selector:
    matchLabels:
      run: org1peer0
  template:
    metadata:
      labels:
        run: org1peer0
    spec:
      containers:
      - name: org1peer0
        # Image used
        image: hyperledger/fabric-peer
        env:
          - name: FABRIC_CFG_PATH
            value: /etc/hyperledger/fabric
          - name: FABRIC_LOGGING_SPEC
            value: DEBUG          
          - name: CORE_PEER_ID
            value: peer0.org1.prototipo.com
          - name: CORE_PEER_ADDRESS
            value: peer0-org1-prototipo:7051
          - name: CORE_PEER_LISTENADDRESS
            value: 0.0.0.0:7051
          - name: CORE_PEER_CHAINCODEADDRESS
            value: peer0-org1-prototipo:7052
          - name: CORE_PEER_CHAINCODELISTENADDRESS
            value: 0.0.0.0:7052
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: /etc/hyperledger/fabric/tls/server.crt
          - name: CORE_PEER_TLS_KEY_FILE
            value: /etc/hyperledger/fabric/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /etc/hyperledger/fabric/tls/ca.crt
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/hyperledger/fabric/users/Admin@org1.prototipo.com/msp
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: "CouchDB"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: couchdb-peer0-org1:5984
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
            value: "blocksaas"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
            value: "blocksaas1988"
            
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/msp
          subPath: crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/msp
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/tls
          subPath: crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/tls
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/users
          subPath: crypto-config/peerOrganizations/org1.prototipo.com/users
        - name: my-pvc-nfs
          mountPath: /var/hyperledger/production
          subPath: crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/chaincode
          subPath: chaincode
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/channel-artifacts
          subPath: channel-artifacts     
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/crypto
          subPath: crypto-config 

      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
          
---
# Expose the port 7051 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer0-org1-prototipo

spec:
  selector:
    run: org1peer0

  ports:
    - name: org1peer0
      port: 7051
    - name: org1peer0-cc
      port: 7052

  type: ClusterIP

---
# Expose the port 7051 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer0-org1-prototipo-nodeport

spec:
  selector:
    run: org1peer0

  ports:
    - name: org1peer0-nodeport
      port: 30751
      nodePort: 30751
    - name: org1peer0-cc-nodeport
      port: 30752
      nodePort: 30752

  type: NodePort
